# Generated by Django 6.0.5 on 2026-05-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
                ('insights_json', models.JSONField(default=list)),
                ('predictions_json', models.JSONField(blank=True, null=True)),
                ('anomalies_json', models.JSONField(blank=True, null=True)),
                ('spending_patterns_json', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'analysis',
                'ordering': ['-analysis_date'],
            },
        ),
    ]
